#a service is responsible for exposing an interface to those pods, 
#which enables network access from either within the cluster or between external processes and the service.
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 5000